### ISSUE TITLE
TensorFlow Version

### ISSUE THREAD

**Issue by Changyu-Guo** [hallieping/DeepHawkes_py3.6#1]
请问 TensorFlow 的版本是多少呢

**Comment by hallieping** [comment]
tensorflow 1.14





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hallieping/DeepHawkes_py3.6"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 晚上8:19
收件人:&nbsp;"hallieping/DeepHawkes_py3.6"<DeepHawkes_py3.6@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hallieping/DeepHawkes_py3.6] TensorFlow Version (#1)





 
请问 TensorFlow 的版本是多少呢

**Comment by Changyu-Guo** [comment]
> tensorflow 1.14
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hallieping/DeepHawkes_py3.6" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月28日(星期三) 晚上8:19 收件人:&nbsp;"hallieping/DeepHawkes_py3.6"<DeepHawkes_py3.6@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[hallieping/DeepHawkes_py3.6] TensorFlow Version (#1) 请问 TensorFlow 的版本是多少呢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的, 谢谢

**Comment by Changyu-Guo** [comment]
好的, 谢谢
